### ISSUE TITLE
Support type handlers

### ISSUE THREAD

**Issue by ShadyHarbinger** [ffhighwind/DapperExtraCRUD#15]
I think supporting type handler calsses by changing the ExtraCrud.cs at line 144 to the one below would be nice:
`bool success = SqlMapper.HasTypeHandler(type) || type.GetInterfaces().Any(ty => ty == typeof(Dapper.SqlMapper.ITypeHandler));`

**Comment by ffhighwind** [comment]
Hi Shady. This is probably the first time I've logged into my github account in 2 years. I have never used Type Handlers from Dapper, but if you have a use case for this I would appreciate it. I need something to add to the tests to ensure it's working properly. If you could send me an example class that would be helpful. Hopefully you respond soon as there's no promises I will keep updating this project in the future.

**Comment by ShadyHarbinger** [comment]
I am sad to hear this great extension for Dapper is not maintained anymore but I understand. I forked and upgraded to the latest NET/Framework versions, removed the support of outdated .NET versions, and upgraded dependencies.
Dapper introduced ITypeHandler classes which can be registered globally.
Check here for a practical example: [Dapper DateOnly/TimeOnly](https://dev.to/karenpayneoregon/dapper-dateonlytimeonly-1ii9)

I do not want to make my own public NuGet because I have never done it. Moreover, I am being honest. I also would not like to maintain it if any issue or request arises because I work a lot. Maybe in the future.
I have not found another Dapper extension providing almost everything needed for data handling in the most performant way. If you know one tell me but migrating my code would be a pain.

**Comment by ffhighwind** [comment]
Yes, it's a lot of work, but I'm glad at least some people appreciate it. I made this project to help with my previous job but I no longer do that job so I don't maintain it. After realizing that the native C# Bulk operations only work for MS SQL I kinda lost a bit of hope with it. I also wanted to try making something closer to Entity since I'm still unsure about the Cache framework in this project.

I can fairly easily update the Nuget with the latest Dapper dependencies. That may get done next week... but I'll have to research the ITypeHandlers a bit more to really understand them and write test cases.

**Comment by ffhighwind** [comment]
I get a MethodAccessException when running my ConsoleTests project using the change you suggested.

System.MethodAccessException: 'Attempt by method 'Dapper.Extra.ExtraCrud.IsValidType(System.Type)' to access method 'Dapper.SqlMapper.HasTypeHandler(System.Type)' failed.'

The 'type' variable during the exception is ConsoleTests.TestDTO. I am unsure why I would be getting an exception by calling SqlMapper.HasTypeHandler. If you have any ideas let me know, otherwise I will just be doing the package updates to the Nuget.

**Comment by ffhighwind** [comment]
As for creating your own Nuget packages you can go to https://www.nuget.org/ and create an account and upload a nupkg file. To turn a project into a nuget file from Visual Studio you just right click on the solution and go to Properties. Then edit the Package tab and check the "generate NuGet package on build". Then when you build the project it should generate the nuget in the bin folder. You may also want to consider signing the assembly. I think this prevents warnings when installing the nuget.

**Comment by ShadyHarbinger** [comment]
> I get a MethodAccessException when running my ConsoleTests project using the change you suggested.
> 
> System.MethodAccessException: 'Attempt by method 'Dapper.Extra.ExtraCrud.IsValidType(System.Type)' to access method 'Dapper.SqlMapper.HasTypeHandler(System.Type)' failed.'
> 
> The 'type' variable during the exception is ConsoleTests.TestDTO. I am unsure why I would be getting an exception by calling SqlMapper.HasTypeHandler. If you have any ideas let me know, otherwise I will just be doing the package updates to the Nuget.

The reason could be the outdated Dapper version. Dapper.SqlMapper.HasTypeHandler did not work for me with the Dapper version used in ExtraCRUD. It worked after I updated the package. I have no idea if it fails only in the console application.

**Comment by ffhighwind** [comment]
I use Dapper.StrongName in ExtraCrud instead of plain Dapper. I think I did this because I was getting naming conflicts that would prevent compiling in one of my work projects. Perhaps StrongName hasn't been updated in a while either. I could try just using plain Dapper again, but I don't have time to do that today. Maybe this weekend.

**Comment by ffhighwind** [comment]
I tried Dapper instead of Dapper.StrongName again and the ConsoleTests project has an exception near the start of main.
My assumption is this is because I use 'Dapper' as my  base namespace which conflicts with the package. This was probably a bad design choice but I was trying to mimic other dapper extensions.

**Comment by ffhighwind** [comment]
I got your suggested code working finally. All I did was update all of the nuget packages in the test project which also seemed to affect the System.Data reference. I'll make another nuget update for what its worth.

As for future issues... keep posting them. I just may not check back to fix them for a while.

**Comment by ShadyHarbinger** [comment]
Great! Thank You!
