### ISSUE TITLE
TracerExtension methods causes ambiguous calls

### ISSUE THREAD

**Issue by ShadyHarbinger** [ffhighwind/DapperExtraCRUD#6]
Duplicated method declarations in TraceExtension class generate ambiguous method errors.
The problem can be resolved by adding assembly resolver manually to project files but it is annoying.
Could You please solve this issue? Oris there a more convenient to avoid these errors?

**Comment by ffhighwind** [comment]
I don't get this error. Are you using both Dapper instead of Dapper.StrongName? 

You can remove the TraceExtensions class/project. There's no point in using it now that I've added try/catch custom exceptions.

**Comment by ShadyHarbinger** [comment]
I use only Dapper and Dapper.ExtraCRUD namespaces.

**Comment by ffhighwind** [comment]
No. I assumed this was related to an issue I had which made me to switch to Dapper.StrongName. 

DapperTracer was intended for debugging my code. It's not intended to be used by users. You're supposed to use DapperTracer by adding a reference the project and removing the Dapper nuget package from the referenced project. The compiler is supposed to use the DapperTracer SqlConnection extension methods instead of Dapper's. This doesn't seem to work anymore. I think the issue is related to compiling under .NET Standard or .NET Core. When I used the project I was only compiling under .NET Framework. The compiler seems like it's adding a reference to Dapper even though I remove it, and this causes the ambiguity.

I can't figure out how to prevent the ambiguity anymore. I'm going to sleep now. If you can figure out how to fix it let me know.

**Comment by ffhighwind** [comment]
I've removed DapperTracer.
